### PR TITLE
Remove labs publishing action

### PR DESCRIPTION
**Pull request by teodutu**
The labs will be entirely hosted on this repo: skeletons and solutions. Therefore, publishing them to `elf.cs.pub.ro` is no longer needed. This makes the `publish-labs.yml` action and the scripts it uses obsolete.

### CODE REVIEW

**Comment by teodutu** [comment]
@edi33416 I've updated the PR's description. Is it clearer now?

**Comment by edi33416** [comment]
Yep. Now everything is clear. Thanks.

Can you please squash and rebase? Then everything is good to go

**Comment by teodutu** [comment]
> Can you please squash and rebase? Then everything is good to go

Done.

**Review by edi33416 — APPROVED** [review]
LGTM

**Pull request merged**
